spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: "jdbc:mysql://localhost:3306/mobilele?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true&serverTimezone=UTC"
    username: root
    password: 1221
  #  servlet:
  #    multipart:
  #      max-file-size: 1MB
  #      max-request-size: 5MB
  mvc:
    hidden-method:
      filter:
        enabled: 'true'

  jpa:
    # Choose either MySQL 8 or MySQL 5 below
    # For MySQL 8
    database-platform: org.hibernate.dialect.MySQLDialect
    #For MySQL 5
    #database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

    #        first create the database, after that seed the data
    defer-datasource-initialization: true
forex:
  api:
    key: ${FOREX_API_KEY:}
    url: "https://openexchangerates.org/api/latest.json?app_id={app_id}"
    base: "USD"

    #  sql:
    #    init:
    #      mode: always

    #Cloudinary Properties
    #cloudinary:
    #api-key:
    #api-secret:
    #cloud-name: